name: Schedule Issue Creation

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '*/10 * * * *'

jobs:
  create_issue:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force Node.js 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Script to Create Issue on Hardcoded Dates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/workflows/create_issue.py
