name: Schedule Issue Creation

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '*/10 * * * *'

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python Script to Create Issue on Hardcoded Dates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 create_issue.py
